name = "opensprinkler-weather"
main = "src/index.ts"
compatibility_date = "2022-07-02"
workers_dev = true
account_id = "3c60789bbe078c2b12886a2701ae72be"

[vars]
BASELINE_ETO = "CloudflareR2"
#BASELINE_ETO_R2_PATH = ""
WEATHER_PROVIDER = "OpenWeatherMap"
GEOCODER = "OpenWeatherMap"
GEOCODER_CACHE = "NullStore"
#GEOCODER_CACHE_KV = ""
TIMEZONE_ID = "Etc/GMT"
#TIMEZONE_ID = "America/Vancouver"
TIMEZONE_LOOKUP = "OpenWeatherMap"
WATERING_SCALE_CACHE = "CloudflareCache"
#OWM_API_KEY = ""
#GOOGLE_MAPS_API_KEY = ""

[[r2_buckets]]
binding = 'BASELINE_ETO_R2_BUCKET'
bucket_name = "opensprinkler-development"
preview_bucket_name = "opensprinkler-development"